# Generated by Django 3.2.15 on 2023-05-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testrapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edit_datum', models.CharField(default='', max_length=30, null=True)),
                ('druktest', models.BooleanField(default=False)),
                ('druktest_datum', models.CharField(default='', max_length=30, null=True)),
                ('luchtest', models.BooleanField(default=False)),
                ('luchtest_datum', models.CharField(default='', max_length=30, null=True)),
                ('druk_cv', models.CharField(default='', max_length=30, null=True)),
                ('flow_cv', models.CharField(default='', max_length=30, null=True)),
                ('standtijd_cv', models.CharField(default='', max_length=30, null=True)),
                ('druktap', models.CharField(default='', max_length=30, null=True)),
                ('standtijd_druktap', models.CharField(default='', max_length=30, null=True)),
                ('npidatatestuitgevoerd', models.BooleanField(default=False)),
                ('npidatatesuitgevoerd_datum', models.CharField(default='', max_length=30, null=True)),
                ('programmeerSD_kaart', models.BooleanField(default=False)),
                ('aanvoertemp', models.IntegerField(default=0, null=True)),
                ('tijd_legionella', models.CharField(default='', max_length=30, null=True)),
                ('frame', models.CharField(default='', max_length=30, null=True)),
                ('sem_gateway', models.CharField(default='', max_length=30, null=True)),
                ('sem_mac_adres', models.CharField(default='', max_length=30, null=True)),
                ('warmtepomp_binnen_ftc_unit', models.CharField(default='', max_length=30, null=True)),
                ('warmtepomp_buiten', models.CharField(default='', max_length=30, null=True)),
                ('procon', models.CharField(default='', max_length=30, null=True)),
                ('ventilatie_wtw', models.CharField(default='', max_length=30, null=True)),
                ('kamstrup_21_rond', models.CharField(default='', max_length=30, null=True)),
                ('kamstrup_403_landis_t230', models.CharField(default='', max_length=30, null=True)),
                ('flowmeter', models.CharField(default='', max_length=30, null=True)),
                ('display_mac_adres_homecontroller', models.CharField(default='', max_length=30, null=True)),
                ('boiler', models.CharField(default='', max_length=30, null=True)),
                ('spinvlies_voldoende', models.BooleanField(default=False)),
                ('bekabeling_voldoende', models.BooleanField(default=False)),
                ('lekvrij_door_blower_door_test', models.BooleanField(default=False)),
                ('spinvlies_zijkanten', models.BooleanField(default=False)),
                ('eindschoonmaak_binnenzijde', models.BooleanField(default=False)),
                ('stikstof_en_vacumeren_module', models.CharField(default='', max_length=30, null=True)),
                ('stikstof_sterkte_bar', models.CharField(default='', max_length=30, null=True)),
                ('stikstof_sterkte_standtijd', models.CharField(default='', max_length=30, null=True)),
                ('vacumeren_module_micron', models.CharField(default='', max_length=30, null=True)),
                ('vacumeren_module_standtijd', models.CharField(default='', max_length=30, null=True)),
                ('lekdetectie', models.BooleanField(default=False)),
                ('lekdetectie_datum', models.CharField(default='', max_length=30, null=True)),
                ('sn_label_op_frame', models.BooleanField(default=False)),
                ('wtw_debieten_control', models.BooleanField(default=False)),
                ('transportlabel_uitgevoerd', models.BooleanField(default=False)),
                ('eindschoonmaak_uitgevoerd', models.BooleanField(default=False)),
                ('transport_gereed', models.BooleanField(default=False)),
                ('transport_gereed_datum', models.CharField(default='', max_length=30, null=True)),
                ('eindcontrole', models.BooleanField(default=False)),
                ('eindcontrole_datum', models.CharField(default='', max_length=30, null=True)),
                ('testrapport_definitief', models.BooleanField(default=False)),
                ('testrapport_definitief_datum', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
    ]
