# Generated by Django 3.2.15 on 2023-02-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mpo', '0002_initial'),
        ('users', '0001_initial'),
        ('testrapport', '0001_initial'),
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrapport',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medewerkerprofile'),
        ),
        migrations.AddField(
            model_name='testrapport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='testrapport',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpo.site'),
        ),
    ]
