# Generated by Django 3.2.15 on 2023-05-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bewoners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aanhef_bewoner', models.CharField(default=True, max_length=30, null=True)),
                ('achternaam_bewoner', models.CharField(default=True, max_length=30, null=True)),
                ('voorletters_bewoner', models.CharField(default=True, max_length=30, null=True)),
                ('phone_bewoner', models.CharField(default=True, max_length=30, null=True)),
                ('tussenvoegsels_bewoner', models.CharField(default=True, max_length=30, null=True)),
                ('email_bewoner', models.EmailField(default=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouwnr', models.CharField(default=True, max_length=30, null=True)),
                ('blok', models.CharField(default=True, max_length=30, null=True)),
                ('straat', models.CharField(default=True, max_length=30, null=True)),
                ('huisnr', models.CharField(default=True, max_length=10, null=True)),
                ('postcode', models.CharField(default=True, max_length=10, null=True)),
                ('bijzonderheden', models.TextField(default=False, null=True)),
                ('koop_huur', models.CharField(default=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bouwkundig',
            fields=[
                ('nokHoogte', models.IntegerField(default=True, null=True)),
                ('nokDiepte', models.IntegerField(default=True, null=True)),
                ('typeDak', models.CharField(default=True, max_length=30, null=True)),
                ('positieBuitendeel', models.CharField(default=True, max_length=30, null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mpo.site')),
            ],
        ),
        migrations.CreateModel(
            name='Icem',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mpo.site')),
                ('icemType', models.CharField(default=True, max_length=2, null=True)),
                ('energieModule', models.CharField(default=True, max_length=30, null=True)),
                ('positieIcem', models.CharField(default=True, max_length=30, null=True)),
                ('aansluitingkanalen', models.CharField(default=True, max_length=30, null=True)),
                ('kwh_meter', models.CharField(default=True, max_length=30, null=True)),
                ('sensoringOptie', models.CharField(default=True, max_length=255, null=True)),
                ('type_prestatie', models.CharField(default=True, max_length=30, null=True)),
                ('koeling', models.CharField(default=True, max_length=30, null=True)),
                ('positieWPmodule', models.CharField(default=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['site'],
            },
        ),
    ]
