# Generated by Django 3.2.15 on 2023-05-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klantmedewerker',
            name='project',
        ),
    ]
