# Generated by Django 3.2.15 on 2023-05-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_klantmedewerker_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectKlantMedewerker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klantMedewerker', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='project.klantmedewerker')),
                ('project', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
