# Generated by Django 3.2.15 on 2023-05-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectklantmedewerker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusonderaanemer',
            name='odernummer',
            field=models.CharField(default=True, max_length=30, null=True),
        ),
    ]
