# Generated by Django 3.2.15 on 2023-05-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_statusonderaanemer_odernummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusonderaanemer',
            name='onderaanemer',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='project.onderaanemerbedrijf'),
        ),
        migrations.AlterField(
            model_name='statusonderaanemer',
            name='project_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
